"""Alert ORM model — table `td.alerts`.

CR-022 Part A. Generated by 3 APScheduler crons (eta_breach, eta_preview,
vip_deadline) plus a manual endpoint. Dispatched via `alert_dispatcher` which
reads `vw_notif_recipients` and sends WhatsApp templates.

State machine:
  abierta   -> notificada  (dispatcher succeeded; notified_at + recipients_count set)
  abierta   -> descartada  (operator dismissed before dispatch)
  notificada -> resuelta   (operator marked as resolved)
  abierta   -> resuelta    (operator self-resolved without notifying)

`dedupe_key` is the cron-side idempotency guard: `tipo:visita_id:date`. We
write a filtered unique index that EXCLUDES descartada rows so dismissed
alerts don't permanently block re-detection of the same condition on the
following sim_clock day.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.core.config import settings
from app.db.base import Base


def _fk(table: str, col: str) -> str:
    return f"{settings.db_schema + '.' if settings.db_schema else ''}{table}.{col}"


TIPOS = ("eta_breach", "eta_preview", "vip_deadline", "manual")
SEVERITIES = ("baja", "media", "alta", "critica")
ESTADOS = ("abierta", "notificada", "resuelta", "descartada")


class Alert(Base):
    __tablename__ = "alerts"
    __table_args__ = (
        CheckConstraint(
            "tipo IN ('eta_breach','eta_preview','vip_deadline','manual')",
            name="ck_alerts_tipo",
        ),
        CheckConstraint(
            "severity IN ('baja','media','alta','critica')",
            name="ck_alerts_severity",
        ),
        CheckConstraint(
            "estado IN ('abierta','notificada','resuelta','descartada')",
            name="ck_alerts_estado",
        ),
        *(({"schema": settings.db_schema},) if settings.db_schema else ()),
    )

    alert_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    tipo: Mapped[str] = mapped_column(String(30), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)

    empresa_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey(
            _fk("empresas", "empresa_id"),
            ondelete="NO ACTION",
            name="fk_alerts_empresa_id_empresas",
        ),
        nullable=False,
        index=True,
    )
    dia_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey(
            _fk("dias_operativos", "dia_id"),
            ondelete="CASCADE",
            name="fk_alerts_dia_id_dias_operativos",
        ),
        nullable=True,
        index=True,
    )
    ruta_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey(
            _fk("rutas", "ruta_id"),
            ondelete="CASCADE",
            name="fk_alerts_ruta_id_rutas",
        ),
        nullable=True,
    )
    visita_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey(
            _fk("visitas", "visita_id"),
            ondelete="CASCADE",
            name="fk_alerts_visita_id_visitas",
        ),
        nullable=True,
    )

    descripcion: Mapped[str] = mapped_column(String(500), nullable=False)
    payload_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    estado: Mapped[str] = mapped_column(
        String(20), nullable=False, default="abierta", server_default="abierta"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    notified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    notified_recipients_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )

    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by_user_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey(
            _fk("users", "user_id"),
            ondelete="SET NULL",
            name="fk_alerts_resolved_by_user_id_users",
        ),
        nullable=True,
    )

    dedupe_key: Mapped[str | None] = mapped_column(String(200), nullable=True)

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"Alert(alert_id={self.alert_id}, tipo={self.tipo!r}, "
            f"severity={self.severity!r}, estado={self.estado!r}, "
            f"empresa_id={self.empresa_id}, visita_id={self.visita_id})"
        )
