"""Pydantic schemas for Driver entity."""
from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class DriverBase(BaseModel):
    empresa_id: int = Field(ge=1)
    vehicle_id: int | None = Field(default=None, ge=1)
    nombre: str = Field(min_length=1, max_length=200)
    rut: str | None = Field(default=None, max_length=20, description="RUT del conductor (ej: 12.345.678-9)")
    phone_e164: str | None = Field(default=None, max_length=20)
    notify_whatsapp: bool = False


class DriverCreate(DriverBase):
    driver_id: str | None = Field(
        default=None,
        max_length=20,
        description="If omitted, autogenerated as `DRV-{empresa_id:02d}{seq:03d}`.",
    )


class DriverUpdate(BaseModel):
    """PATCH — empresa_id cannot change here (admin DDL only)."""

    vehicle_id: int | None = Field(default=None, ge=1)
    nombre: str | None = Field(default=None, min_length=1, max_length=200)
    rut: str | None = Field(default=None, max_length=20, description="RUT del conductor (ej: 12.345.678-9)")
    phone_e164: str | None = Field(default=None, max_length=20)
    notify_whatsapp: bool | None = None
    activo: bool | None = None


class DriverOut(DriverBase):
    driver_id: str
    opted_in_at: datetime | None = None
    activation_token: str | None = None
    activation_used_at: datetime | None = None
    activo: bool
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class RegenerateActivationResponse(BaseModel):
    driver_id: str
    activation_token: str
    activation_link: str
    expires_at: datetime | None = None
